set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property PACKAGE_PIN K17 [get_ports clock_125Mhz]
set_property PACKAGE_PIN M15 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports clock_125Mhz]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports Anode_Activate]
set_property PACKAGE_PIN H15 [get_ports Anode_Activate]
set_property PACKAGE_PIN T14 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN T15 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN P14 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN R14 [get_ports {LED_out[3]}]

set_property PACKAGE_PIN V12 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN W16 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN J15 [get_ports {LED_out[0]}]

